/* clang-format off */

#include "aw_reg_dbg.h"

#ifndef AW_NUM_BRANCHES
//Note: this constant is 32 in 4ln and evb
//      hopefully we can use this def just
//      to get this file to compile but use the
//      IP local def in the code
#define AW_NUM_BRANCHES                    64
#endif

#ifndef AW_TBUS_NUM_SAMPLES
// Note: this constant is 2 in both 4ln and 16ln
//       an undefined in evb
#define AW_TBUS_NUM_SAMPLES                2
#endif


typedef int (*aw_pmd_cmn_clkgen_refdiv_set)(mss_access_t *mss, uint32_t div);
typedef int (*aw_pmd_cmn_clkgen_refdiv_get)(mss_access_t *mss, uint32_t * div);
typedef int (*aw_pmd_anlt_logical_lane_num_set )(mss_access_t *mss, uint32_t logical_lane, uint32_t an_no_attached);
typedef int (*aw_pmd_anlt_logical_lane_num_get )(mss_access_t *mss, uint32_t * logical_lane, uint32_t * an_no_attached);
typedef int (*aw_pmd_anlt_auto_neg_adv_ability_set )(mss_access_t *mss, uint32_t *adv_ability, uint32_t *fec_ability, uint32_t nonce);
typedef int (*aw_pmd_anlt_auto_neg_adv_ability_get )(mss_access_t *mss, uint32_t * adv_ability, uint32_t *fec_ability);
typedef int (*aw_pmd_anlt_auto_neg_config_set )(mss_access_t *mss, uint32_t status_check_disable, uint32_t next_page_en, uint32_t an_no_nonce_check);
typedef int (*aw_pmd_anlt_auto_neg_config_get )(mss_access_t *mss, uint32_t * status_check_disable, uint32_t * next_page_en, uint32_t * an_no_nonce_check);
typedef int (*aw_pmd_anlt_auto_neg_start_set )(mss_access_t *mss, uint32_t start);
typedef int (*aw_pmd_anlt_auto_neg_start_get )(mss_access_t *mss, uint32_t * start);
typedef int (*aw_pmd_anlt_auto_neg_status_get )(mss_access_t *mss, uint32_t * link_good);
//typedef int (*aw_pmd_anlt_auto_neg_result_get )(mss_access_t *mss, uint8_t no_consortium, uint32_t * an_result);
typedef int (*aw_pmd_anlt_auto_neg_result_get )(mss_access_t *mss, uint32_t * an_result);
typedef int (*aw_pmd_anlt_auto_neg_page_rx_get)(mss_access_t *mss, uint32_t *an_mr_page_rx, uint64_t *an_rx_link_code_word);
typedef int (*aw_pmd_anlt_auto_neg_next_page_set)(mss_access_t *mss, uint64_t an_tx_np);
typedef int (*aw_pmd_anlt_auto_neg_newdef_get)(mss_access_t *mss, aw_an_spec_t *newdef_get);
typedef int (*aw_pmd_anlt_auto_neg_rs_fec_int_ena_get )(mss_access_t *mss,  uint32_t * an_rs_fec_int_ena);
typedef int (*aw_pmd_anlt_auto_neg_next_page_oui_compare_set)(mss_access_t *mss, uint32_t np_expected_oui);
typedef int (*aw_pmd_anlt_link_training_en_set )(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_anlt_link_training_en_get )(mss_access_t *mss, uint32_t * en);
//typedef int (*aw_pmd_anlt_link_training_config_set )(mss_access_t *mss, uint32_t width, uint32_t clause, uint32_t mod);
typedef int (*aw_pmd_anlt_link_training_config_set )(mss_access_t *mss, uint32_t width, uint32_t clause);
typedef int (*aw_pmd_anlt_link_training_config_get )(mss_access_t *mss, uint32_t * width, uint32_t * clause);
typedef int (*aw_pmd_anlt_link_training_prbs_seed_set )(mss_access_t *mss, uint32_t clause, uint32_t logical_lane);
typedef int (*aw_pmd_anlt_link_training_start_set )(mss_access_t *mss, uint32_t start);
typedef int (*aw_pmd_anlt_link_training_start_get )(mss_access_t *mss, uint32_t * start);
typedef int (*aw_pmd_anlt_link_training_status_get )(mss_access_t *mss, uint32_t * lt_running, uint32_t * lt_done, uint32_t * lt_training_failure, uint32_t * lt_rx_ready);
typedef int (*aw_pmd_anlt_link_training_timeout_enable_set )(mss_access_t *mss, uint32_t enable);
typedef int (*aw_pmd_ctrl_map_en_set)(mss_access_t *mss, uint32_t anlt_ctrl_map_en);
typedef int (*aw_pmd_refclk_termination_set)(mss_access_t *mss, aw_refclk_term_mode_t lsrefbuf_term_mode);
typedef int (*aw_pmd_refclk_termination_get)(mss_access_t *mss, aw_refclk_term_mode_t *lsrefbuf_term_mode);
typedef int (*aw_pmd_rx_termination_set)(mss_access_t *mss, aw_acc_term_mode_t acc_term_mode);
typedef int (*aw_pmd_rx_termination_get)(mss_access_t *mss, aw_acc_term_mode_t *acc_term_mode);
typedef int (*aw_pmd_force_signal_detect_config_set)(mss_access_t *mss, aw_force_sigdet_mode_t sigdet_mode);
typedef int (*aw_pmd_force_signal_detect_config_get)(mss_access_t *mss, aw_force_sigdet_mode_t *sigdet_mode);
typedef int (*aw_pmd_tx_disable_set)(mss_access_t *mss, uint32_t tx_disable);
typedef int (*aw_pmd_tx_disable_get)(mss_access_t *mss, uint32_t *tx_disable);
// typedef int (*aw_pmd_rx_disable_pin_override_set)(mss_access_t *mss, int override_enable);}
// typedef int (*aw_pmd_rx_disable_pin_override_get)(mss_access_t *mss, int *override_enable);}
// typedef int (*aw_pmd_rx_disable_set )(mss_access_t *mss, int rx_disable);}
// typedef int (*aw_pmd_rx_disable_get)(mss_access_t *mss, int *rx_disable);}
typedef int (*aw_pmd_txfir_config_set)(mss_access_t *mss, aw_txfir_config_t txfir_cfg, uint32_t fir_ovr_enable);
typedef int (*aw_pmd_txfir_config_get)(mss_access_t *mss, aw_txfir_config_t *txfir_cfg);
typedef int (*aw_pmd_tx_tap_mode_get)(uint32_t *max_rng_cm3, uint32_t *max_rng_cm2, uint32_t *max_rng_cm1, uint32_t *max_rng_c1, uint32_t *max_rng_c0);
typedef int (*aw_pmd_tx_pam4_precoder_override_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_tx_pam4_precoder_override_get)(mss_access_t *mss, uint32_t *en);
typedef int (*aw_pmd_tx_pam4_precoder_enable_set)(mss_access_t *mss, uint32_t gray_en, uint32_t plusd_en);
typedef int (*aw_pmd_tx_pam4_precoder_enable_get)(mss_access_t *mss, uint32_t *gray_en, uint32_t *plusd_en);
typedef int (*aw_pmd_rx_pam4_precoder_override_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_rx_pam4_precoder_override_get)(mss_access_t *mss, uint32_t *en);
typedef int (*aw_pmd_rx_pam4_precoder_enable_set)(mss_access_t *mss, uint32_t gray_en, uint32_t plusd_en);
typedef int (*aw_pmd_rx_pam4_precoder_enable_get)(mss_access_t *mss, uint32_t *gray_en, uint32_t *plusd_en);
typedef int (*aw_pmd_remote_loopback_set)(mss_access_t *mss, uint32_t remote_loopback_enable);
typedef int (*aw_pmd_remote_loopback_get)(mss_access_t *mss, uint32_t *remote_loopback_enable);
typedef int (*aw_pmd_fep_data_set)(mss_access_t *mss, uint32_t datapath_en);
typedef int (*aw_pmd_fep_data_get)(mss_access_t *mss, uint32_t *datapath_en);
typedef int (*aw_pmd_tx_dcd_iq_cal)(mss_access_t *mss, uint32_t enable_d);
typedef int (*aw_pmd_fep_clock_set)(mss_access_t *mss, uint8_t clock_en);
typedef int (*aw_pmd_tx_postdiv_loopback_ena_set)(mss_access_t *mss, uint8_t postdiv_loopback_ena);
typedef int (*aw_pmd_tx_postdiv_loopback_ena_get)(mss_access_t *mss, uint8_t *postdiv_loopback_ena);
typedef int (*aw_pmd_fep_clock_get)(mss_access_t *mss, uint32_t *clock_en);
typedef int (*aw_pmd_analog_loopback_set)(mss_access_t *mss, uint32_t analog_loopback_enable);
typedef int (*aw_pmd_analog_loopback_get)(mss_access_t *mss, uint32_t *analog_loopback_enable);
typedef int (*aw_pmd_fes_loopback_set)(mss_access_t *mss, uint32_t fes_loopback_enable);
typedef int (*aw_pmd_fes_loopback_get)(mss_access_t *mss, uint32_t *fes_loopback_enable);
typedef int (*aw_pmd_nep_loopback_set)(mss_access_t *mss, uint32_t nep_loopback_enable);
typedef int (*aw_pmd_nep_loopback_get)(mss_access_t *mss, uint32_t *nep_loopback_enable);
typedef int (*aw_pmd_tx_polarity_set)(mss_access_t *mss, uint32_t tx_pol_flip);
typedef int (*aw_pmd_tx_polarity_get)(mss_access_t *mss, uint32_t *tx_pol_flip);
typedef int (*aw_pmd_rx_polarity_set)(mss_access_t *mss, uint32_t rx_pol_flip);
typedef int (*aw_pmd_rx_polarity_get)(mss_access_t *mss, uint32_t *rx_pol_flip);
typedef int (*aw_pmd_tx_hbridge_set)(mss_access_t *mss, tx_hbridge_t *tx_hbridge_st);
typedef int (*aw_pmd_tx_hbridge_get)(mss_access_t *mss, uint32_t *msb, uint32_t *lsb);
// typedef int (*aw_pmd_lane_cfg_set)(mss_access_t *mss, lane_cfg_t lane_cfg);}
// typedef int (*aw_pmd_lane_cfg_get)(mss_access_t *mss, lane_cfg_t *lane_cfg);}
typedef int (*aw_pmd_rx_dfe_adapt_set)(mss_access_t *mss, uint32_t dfe_adapt_enable);
typedef int (*aw_pmd_rx_dfe_adapt_get)(mss_access_t *mss, uint32_t *dfe_adapt_enable);
typedef int (*aw_pmd_rx_ctle_adapt_set)(mss_access_t *mss, uint32_t ctle_adapt_enable, uint32_t ctle_boost_a);
typedef int (*aw_pmd_rx_ctle_adapt_get)(mss_access_t *mss, uint32_t *ctle_adapt_enable, uint32_t *ctle_boost_a);
typedef int (*aw_pmd_rx_background_adapt_enable_set)(mss_access_t *mss, uint8_t rx_background_adapt);
typedef int (*aw_pmd_rx_background_adapt_enable_get)(mss_access_t *mss, uint32_t *rx_bkgrnd_adapt_enable);
typedef int (*aw_pmd_rx_autoeq_set)(mss_access_t *mss, uint32_t rx_autoeq_enable);
typedef int (*aw_pmd_rx_autoeq_get)(mss_access_t *mss, uint32_t *rx_autoeq_enable);
typedef int (*aw_pmd_rx_ffe_tap_count_set)(mss_access_t *mss, uint32_t tap_count);
typedef int (*aw_pmd_rx_ffe_tap_count_get)(mss_access_t *mss, uint32_t* tap_count);
typedef int (*aw_pmd_rx_roaming_windows_set)(mss_access_t *mss, aw_rx_roaming_mode_t mode, uint8_t window_select1, uint8_t window_select2);
typedef int (*aw_pmd_rx_roaming_windows_get)(mss_access_t *mss, aw_rx_roaming_mode_t *mode, uint8_t *window_select1, uint8_t *window_select2);
typedef int (*aw_pmd_rx_vga_cap_set)(mss_access_t *mss, uint32_t vga_cap);
typedef int (*aw_pmd_rx_vga_cap_adapt_set)(mss_access_t *mss, vga_opt_t *opts);
typedef int (*aw_pmd_rx_vga_cap_get)(mss_access_t *mss, uint32_t *vga_cap);
typedef int (*aw_pmd_rx_vga_cap_adapt_get)(mss_access_t *mss, vga_opt_t *opts);
typedef int (*aw_pmd_rxeq_prbs_set)(mss_access_t *mss, uint32_t prbs_en);
typedef int (*aw_pmd_rxeq_prbs_get)(mss_access_t *mss, uint32_t *prbs_en);
typedef int (*aw_pmd_rx_c0_adapt_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_rx_cdr_offset_set)(mss_access_t *mss, uint32_t use_custom_cdr_offset, uint32_t cdr_offset, uint32_t cdr_dir);
typedef int (*aw_pmd_rx_signal_detect_get)(mss_access_t *mss, uint32_t *signal_detect);
typedef int (*aw_pmd_rx_signal_detect_check)(mss_access_t *mss, uint32_t signal_detect_expected);
typedef int (*aw_pmd_tx_ppm_get)(mss_access_t *mss, uint32_t timing_window, uint32_t timeout_us, double *tx_ppm, double *vco_freq, double refclk_freq);
typedef int (*aw_pmd_rx_ppm_get)(mss_access_t *mss, uint32_t timing_window, uint32_t timeout_us, double *rx_ppm, double *vco_freq, double refclk_freq);
typedef int (*aw_pmd_rx_lock_status_get)(mss_access_t *mss, uint32_t *pmd_rx_lock);
typedef int (*aw_pmd_rx_dcdiq_get)(mss_access_t *mss, aw_dcdiq_data_t *rx_dcdiq_data);
typedef int (*aw_pmd_tx_dcdiq_get)(mss_access_t *mss, aw_dcdiq_data_t *tx_dcdiq_data);
typedef int (*aw_pmd_rx_afe_get)(mss_access_t *mss, aw_afe_data_t *rx_afe_data);
typedef int (*aw_pmd_rx_invert_datapath)(mss_access_t *mss, char modulation_mode[], uint32_t gray_code_en, uint32_t invert_en);
typedef int (*aw_pmd_tx_invert_datapath)(mss_access_t *mss, char modulation_mode[], uint32_t gray_code_en, uint32_t invert_en);
typedef int (*aw_pmd_rx_chk_config_set)(mss_access_t *mss, aw_bist_pattern_t pattern, aw_bist_mode_t mode, uint64_t udp, uint32_t lock_thresh, uint32_t timer_thresh);
typedef int (*aw_pmd_rx_chk_config_get)(mss_access_t *mss, aw_bist_pattern_t *pattern, aw_bist_mode_t *mode, uint64_t *udp, uint32_t *lock_thresh, uint32_t *timer_thresh);
typedef int (*aw_pmd_rx_chk_en_set)(mss_access_t *mss, uint32_t enable);
typedef int (*aw_pmd_rx_chk_en_get)(mss_access_t *mss, uint32_t *enable);
typedef int (*aw_pmd_rx_chk_lock_state_get)(mss_access_t *mss, uint32_t *rx_bist_lock);
typedef int (*aw_pmd_rx_chk_err_count_state_get)(mss_access_t *mss, uint64_t *err_count, uint32_t *err_count_done, uint32_t *err_count_overflown);
typedef int (*aw_pmd_rx_chk_err_count_state_clear)(mss_access_t *mss);
typedef int (*aw_pmd_tx_gen_config_set)(mss_access_t *mss, aw_bist_pattern_t pattern, uint64_t udp);
typedef int (*aw_pmd_tx_gen_config_get)(mss_access_t *mss, aw_bist_pattern_t *pattern, uint64_t *udp);
typedef int (*aw_pmd_tx_gen_en_set)(mss_access_t *mss, uint32_t enable);
typedef int (*aw_pmd_tx_gen_en_get)(mss_access_t *mss, uint32_t *enable);
typedef int (*aw_pmd_tx_gen_err_inject_config_set)(mss_access_t *mss, uint64_t err_pattern, uint32_t err_rate);
typedef int (*aw_pmd_tx_gen_err_inject_config_get)(mss_access_t *mss, uint64_t *err_pattern, uint32_t *err_rate);
typedef int (*aw_pmd_tx_gen_err_inject_en_set)(mss_access_t *mss, uint32_t enable);
typedef int (*aw_pmd_tx_gen_err_inject_en_get)(mss_access_t *mss, uint32_t *enable);
typedef int (*aw_pmd_rx_sweep_demapper)(mss_access_t *mss, uint32_t npam4_nrz, uint32_t timeout_us);
typedef int (*aw_pmd_gen_tx_swap_msb_lsb_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_gen_tx_swap_msb_lsb_get)(mss_access_t *mss, uint32_t *en);
typedef int (*aw_pmd_gen_rx_swap_msb_lsb_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_gen_rx_swap_msb_lsb_get)(mss_access_t *mss, uint32_t *en);
typedef int (*aw_pmd_uc_ucode_load)(mss_access_t *mss, aw_ucode_t *ucode, uint32_t ucode_len);
// typedef int (*aw_pmd_pll_lock_get)(mss_access_t *mss, uint32_t *pll_lock);
typedef int (*aw_pmd_pll_lock_max_set)(mss_access_t *mss, uint32_t val);
typedef int (*aw_pmd_pll_lock_min_set)(mss_access_t *mss, uint32_t val);
typedef int (*aw_pmd_pll_lock_get)(mss_access_t *mss, uint32_t *pll_lock,uint32_t check_en, uint32_t expected_val);
typedef int (*aw_pmd_uc_diag_reg_dump)(mss_access_t *mss, aw_uc_diag_regs_t *uc_diag);
typedef int (*aw_pmd_uc_diag_logging_en_set)(mss_access_t *mss, uint32_t uc_log_cmn_en, uint32_t uc_log_tx_en, uint32_t uc_log_rx_en);
typedef int (*aw_pmd_uc_diag_logging_en_get)(mss_access_t *mss, uint32_t *uc_log_cmn_en, uint32_t *uc_log_tx_en, uint32_t *uc_log_rx_en);
typedef int (*aw_pmd_iso_ref_ls_en_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_cmn_pstate_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_cmn_pstate_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_iso_cmn_state_req_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_cmn_state_ack_get)(mss_access_t *mss, uint32_t *cmn_state_ack);
typedef int (*aw_pmd_iso_tx_reset_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_tx_reset_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_iso_rx_reset_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_rx_reset_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_iso_tx_rate_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_tx_rate_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_iso_rx_rate_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_rx_rate_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_iso_tx_pstate_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_tx_pstate_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_iso_rx_pstate_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_rx_pstate_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_iso_tx_width_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_tx_width_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_iso_rx_width_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_rx_width_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_iso_tx_state_req_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_rx_state_req_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_iso_tx_state_ack_get)(mss_access_t *mss, uint32_t *tx_state_ack);
typedef int (*aw_pmd_iso_rx_state_ack_get)(mss_access_t *mss, uint32_t *rx_state_ack);
typedef int (*aw_pmd_isolate_cmn_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_isolate_cmn_get)(mss_access_t *mss, uint32_t *en);
typedef int (*aw_pmd_isolate_lane_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_isolate_lane_tx_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_isolate_lane_rx_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_isolate_lane_txrx_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_isolate_lane_get)(mss_access_t *mss, uint32_t *en);
typedef int (*aw_pmd_cmn_r2l_hsref_sel_set)(mss_access_t *mss, uint32_t sel);
typedef int (*aw_pmd_cmn_r2l0_lsref_sel_set)(mss_access_t *mss, uint32_t sel);
typedef int (*aw_pmd_cmn_r2l1_lsref_sel_set)(mss_access_t *mss, uint32_t sel);
typedef int (*aw_pmd_cmn_l2r_hsref_sel_set)(mss_access_t *mss, uint32_t sel);
typedef int (*aw_pmd_cmn_l2r0_lsref_sel_set)(mss_access_t *mss, uint32_t sel);
typedef int (*aw_pmd_cmn_l2r1_lsref_sel_set)(mss_access_t *mss, uint32_t sel);
typedef int (*aw_pmd_cmn_r2l_hsref_sel_get)(mss_access_t *mss, uint32_t *sel);
typedef int (*aw_pmd_cmn_r2l0_lsref_sel_get)(mss_access_t *mss, uint32_t *sel);
typedef int (*aw_pmd_cmn_r2l1_lsref_sel_get)(mss_access_t *mss, uint32_t *sel);
typedef int (*aw_pmd_cmn_l2r_hsref_sel_get)(mss_access_t *mss, uint32_t *sel);
typedef int (*aw_pmd_cmn_l2r0_lsref_sel_get)(mss_access_t *mss, uint32_t *sel);
typedef int (*aw_pmd_cmn_l2r1_lsref_sel_get)(mss_access_t *mss, uint32_t *sel);
typedef int (*aw_pmd_cmn_lsref_sel_set)(mss_access_t *mss, uint32_t ref_sel);
typedef int (*aw_pmd_cmn_lsref_sel_get)(mss_access_t *mss, uint32_t *ref_sel);
typedef int (*aw_pmd_pcie_cmn_lsref_25m_set)(mss_access_t *mss, uint32_t lsref_25m);
typedef int (*aw_pmd_pcie_cmn_lsref_25m_get)(mss_access_t *mss, uint32_t *lsref_25m);
typedef int (*aw_pmd_gen_tx_en_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_gen_tx_en_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_rx_error_cnt_done_get)(mss_access_t *mss, uint32_t *err_count_done);
typedef int (*aw_pmd_iso_request_cmn_state_change)(mss_access_t *mss, aw_cmn_pstate_t cmn_pstate, uint32_t timeout_us);
typedef int (*aw_pmd_iso_request_tx_state_change)(mss_access_t *mss, aw_pstate_t tx_pstate, uint32_t tx_rate, uint32_t tx_width, uint32_t timeout_us);
typedef int (*aw_pmd_iso_request_rx_state_change)(mss_access_t *mss, aw_pstate_t rx_pstate, uint32_t rx_rate, uint32_t rx_width, uint32_t timeout_us);
typedef int (*aw_pmd_rx_check_cdr_lock)(mss_access_t *mss, uint32_t timeout_us);
typedef int (*aw_pmd_rx_check_bist)(mss_access_t *mss, aw_bist_mode_t bist_mode, uint32_t timer_threshold, uint32_t rx_width, uint32_t timeout_us, int32_t expected_errors);
typedef int (*aw_pmd_rx_prefec_clear)(mss_access_t *mss);
typedef int (*aw_pmd_rx_prefec_enable_get)(mss_access_t *mss, uint32_t *enable);
typedef int (*aw_pmd_rx_prefec_enable_set)(mss_access_t *mss, uint32_t enable);
typedef int (*aw_pmd_rx_prefec_poll)(mss_access_t *mss, uint32_t timeout_us);
typedef int (*aw_pmd_rx_prefec_config_get)(mss_access_t *mss, uint32_t *corr_num_syms, uint32_t *symbol_size, uint32_t *wall_mode, uint32_t *sym_per_cw, uint32_t *skip_syms, uint32_t *timer_num_cw);
typedef int (*aw_pmd_rx_prefec_config_set)(mss_access_t *mss, uint32_t corr_num_syms, uint32_t symbol_size, uint32_t wall_mode, uint32_t sym_per_cw, uint32_t skip_syms, uint32_t timer_num_cw);
typedef int (*aw_pmd_rx_prefec_get_results)(mss_access_t *mss, uint32_t *hist);
typedef int (*aw_pmd_eqeval_type_set)(mss_access_t *mss, uint32_t eq_type);
typedef int (*aw_pmd_eqeval_req_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_eqeval_ack_get)(mss_access_t *mss, uint32_t *eqeval_ack);
typedef int (*aw_pmd_eqeval_incdec_get)(mss_access_t *mss, uint32_t *incdec);
typedef int (*aw_pmd_rx_equalize)(mss_access_t *mss, aw_eq_type_t eq_type, uint32_t timeout_us);
typedef int (*aw_pmd_tx_rxdet_req_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_tx_rxdet)(mss_access_t *mss, uint32_t rxdet_expected, uint32_t timeout_us);
typedef int (*aw_pmd_tx_beacon_en_set)(mss_access_t *mss, uint32_t value);
typedef int (*aw_pmd_tx_beacon_en_get)(mss_access_t *mss, uint32_t *value);
typedef int (*aw_pmd_tx_pll_fine_code_get)(mss_access_t *mss, uint32_t * tx_pll_fine_code, uint32_t center_code, int tolerance);
typedef int (*aw_pmd_tx_pll_coarse_code_get)(mss_access_t *mss, uint32_t * tx_pll_coarse_code, uint32_t center_code, int tolerance);
typedef int (*aw_pmd_rx_pll_fine_code_get)(mss_access_t *mss, uint32_t * rx_pll_fine_code, uint32_t center_code, int tolerance);
typedef int (*aw_pmd_rx_pll_coarse_code_get)(mss_access_t *mss, uint32_t * rx_pll_coarse_code, uint32_t center_code, int tolerance);
typedef int (*aw_pmd_cmn_pll_fine_code_get)(mss_access_t *mss, uint32_t * cmn_pll_fine_code, uint32_t center_code, int tolerance);
typedef int (*aw_pmd_cmn_pll_coarse_code_get)(mss_access_t *mss, uint32_t * cmn_pll_coarse_code, uint32_t center_code, int tolerance);
typedef int (*aw_pmd_rd_data_pipeline_stages_set)(mss_access_t *mss, uint32_t stages);
typedef int (*aw_pmd_rd_data_pipeline_stages_get)(mss_access_t *mss, uint32_t* stages);
typedef int (*aw_pmd_measure_pmon)(mss_access_t *mss, uint32_t pmon_sel, uint32_t pvt_measure_timing_window, uint32_t timeout_us, uint32_t * pvt_measure_result);
typedef int (*aw_pmd_atest_en)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_atest_cmn_capture)(mss_access_t *mss, uint32_t atest_addr, uint32_t atest_term, uint32_t * atest_adc_val);
typedef int (*aw_pmd_atest_tx_capture)(mss_access_t *mss, uint32_t atest_addr, uint32_t atest_term, uint32_t * atest_adc_val);
typedef int (*aw_pmd_atest_rx_a_capture)(mss_access_t *mss, uint32_t atest_addr, uint32_t atest_term, uint32_t * atest_adc_val);
typedef int (*aw_pmd_atest_rx_b_capture)(mss_access_t *mss, uint32_t atest_addr, uint32_t atest_term, uint32_t * atest_adc_val);
typedef int (*aw_pmd_atest_adc_power)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_atest_adc_temp_capture)(mss_access_t *mss, uint32_t iterations, aw_adc_temp_data_t *mean_data);
typedef int (*aw_pmd_atest_adc_temp_get)(mss_access_t *mss, aw_adc_temp_calibration_t *calibration, aw_adc_temp_method_t method, uint32_t iterations, aw_adc_temp_data_t *measured_data, float *result_temp);
typedef int (*aw_pmd_rx_cdr_lock_get)(mss_access_t *mss, uint32_t *rx_cdr_lock);
typedef int (*aw_pmd_lcpll_vco_counter_get)(mss_access_t *mss, uint32_t timing_window, double *lcpll_ppm, double *vco_freq, double refclk_freq);
typedef int (*aw_pmd_rx_cdr_offset_get)(mss_access_t *mss, uint32_t *use_custom_cdr_offset, uint32_t *cdr_offset, uint32_t *cdr_dir);
typedef int (*aw_pmd_read_status)(mss_access_t *mss, int branch);
typedef int (*aw_pmd_pause_background)(mss_access_t *mss, uint32_t pause_enable);
typedef int (*aw_pmd_tracebuffer_config_enable)(mss_access_t *mss, uint32_t clk_sel, uint32_t enable);
typedef int (*aw_pmd_tracebuffer_config_get)(mss_access_t *mss, aw_pmd_tracebuffer_mode_t *tbmode, uint32_t *samples_per_cycle);
typedef int (*aw_pmd_tracebuffer_config_set)(mss_access_t *mss, aw_pmd_tracebuffer_mode_t tbmode, uint32_t samples_per_cycle);
typedef int (*aw_pmd_read_tracebuffer)(mss_access_t *mss, uint32_t *tb_data, int tb_size);
typedef int (*aw_pmd_convert_data_signed)(uint32_t data);
typedef int (*aw_pmd_read_tracebuffer_adc)(mss_access_t *mss, int num_samples, int adc_data[num_samples][AW_NUM_BRANCHES]);
typedef int (*aw_pmd_tbus_client_config_get)(mss_access_t *mss, uint32_t *block_id, uint32_t *signal_id, uint32_t *trigger, uint32_t *continuous_sample);
typedef int (*aw_pmd_tbus_client_config_set)(mss_access_t *mss, uint32_t block_id, uint32_t signal_id, uint32_t trigger, uint32_t continuous_sample);
typedef int (*aw_pmd_read_tracebuffer_demapper)(mss_access_t *mss, int32_t demapper_data[2][AW_TBUS_NUM_SAMPLES], uint32_t branch_id, uint32_t is_ffe);
typedef int (*aw_pmd_read_tracebuffer_general)(mss_access_t *mss, int32_t tb_data_out[AW_TBUS_NUM_SAMPLES], int tbus_block_id, uint32_t signal_id, int fp_lsb, int fp_msb, int fp_si);
typedef int (*aw_pmd_read_tracebuffer_ffe)(mss_access_t *mss, int num_samples, int32_t *ffe_data, int branch_id);
typedef int (*aw_pmd_read_tracebuffer_itr_dlpf_int)(mss_access_t *mss, int num_samples, int32_t *itr_dlpf_int);
typedef int (*aw_pmd_read_tracebuffer_quantizer_err)(mss_access_t *mss, int num_samples, int32_t *qztr_err_data, int branch_id);
typedef int (*aw_pmd_cmn_ssc_config)(mss_access_t *mss, double lsref_mhz, double lcpll_mhz, int ppm_downspread);
typedef int (*aw_pmd_cmn_ssc_en_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_sram_clk_div_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_sram_clk_div_get)(mss_access_t *mss, uint32_t *en);
typedef int (*aw_pmd_rx_burst_mode_config_set)(mss_access_t *mss, uint32_t pam_mode, uint32_t burst_threshold, uint32_t burst_mode);
typedef int (*aw_pmd_rx_burst_mode_config_get)(mss_access_t *mss, uint32_t *pam_mode, uint32_t *burst_threshold, uint32_t *burst_mode);
typedef int (*aw_pmd_rx_burst_err_cnt_get)(mss_access_t *mss, uint32_t *burst_err_cnt);
typedef int (*aw_pmd_rx_burst_mode_stats_get)(mss_access_t *mss, uint32_t exp_data[], uint32_t rec_data[], uint32_t xor_data[]);
typedef int (*aw_pmd_rx_gray_code_mapping_get)(mss_access_t *mss, uint8_t *gray_code_map);
typedef int (*aw_pmd_rx_gray_code_mapping_set)(mss_access_t *mss, uint8_t gray_code_map);
typedef int (*aw_pmd_tx_gray_code_mapping_get)(mss_access_t *mss, uint8_t *gray_code_map);
typedef int (*aw_pmd_tx_gray_code_mapping_set)(mss_access_t *mss, uint8_t gray_code_map);
typedef int (*aw_pmd_tx_perf_settings)(mss_access_t *mss, uint8_t perf_mode);
typedef int (*aw_pmd_cmn_bias_bandgap_force_startup)(mss_access_t *mss);
typedef int (*aw_pmd_sris_set)(mss_access_t *mss, uint32_t en);
typedef int (*aw_pmd_sris_get)(mss_access_t *mss, uint32_t *en);
typedef int (*aw_pmd_rx_active_branches_get)(mss_access_t *mss, uint32_t * active_branches);
typedef int (*aw_pmd_fw_version_get)(mss_access_t *mss, aw_version_t *version_st);
typedef int (*aw_pmd_rx_dfe_ratio_set)(mss_access_t *mss, uint32_t enable, uint32_t use_auto_lookup_dfe_ratio, double custom_dfe_ratio);
typedef int (*aw_pmd_rx_dfe_ratio_get)(mss_access_t *mss, uint32_t* enable, uint32_t* use_auto_lookup_dfe_ratio, double* custom_dfe_ratio);


//bfn defined fns
typedef int (*aw_pmd_rd_csr)(mss_access_t *mss, uint32_t addr, uint32_t *rdata);
typedef int (*aw_pmd_wr_csr)(mss_access_t *mss, uint32_t addr, uint32_t wdata);
typedef int (*aw_pmd_mss_reset)(mss_access_t *mss);
typedef int (*aw_pmd_fw_load)(mss_access_t *mss, char *path);
typedef int (*aw_pmd_one_time_pgm)(mss_access_t *mss);
typedef int (*aw_pmd_cur_rate_width_pstate)(mss_access_t *mss, uint32_t *tx_rate, uint32_t *tx_width, uint32_t *tx_pstate, uint32_t *rx_rate, uint32_t *rx_width, uint32_t *rx_pstate);
typedef int (*aw_pmd_rxmfsm_eq_check_rxdisable_set)(mss_access_t *mss, uint32_t val);
typedef int (*aw_pmd_lt_info_get)(mss_access_t *mss, uint32_t * lt_fsm_st, uint32_t * frame_lock);
typedef int (*aw_pmd_reg_defs_get)(aw_reg_defs_t **regs, aw_fld_defs_t **flds, char **cmnts, aw_reg_defs_t **vregs, aw_fld_defs_t **vflds, char **vcmnts);
typedef int (*aw_pmd_speed_to_rate_and_width)(mss_access_t *mss, uint32_t serdes_speed, bool is_pam4, uint32_t *rate, uint32_t *width);
typedef int (*aw_pmd_rx_dig_pwr_det_threshold_get)(mss_access_t *mss, uint32_t *adc_valid_thresh_nt, uint32_t *adc_invalid_thresh_nt );
typedef int (*aw_pmd_rx_dig_pwr_det_threshold_set)(mss_access_t *mss, uint32_t adc_valid_thresh_nt, uint32_t adc_invalid_thresh_nt );

// virtual field APIs
//
// Note: bf-gen.py does not expand include files so the virtual field vectors
// are not generated by this line. However, the types need to be defined for
// the vector table (below) to be initialized. There is a separate call to
// bf-gen.py passing this .h file to generate the virtual field APIs.
//
#include "vfld_vec_type.h"

// end-of-types

typedef struct aw_serdes_driver_vector_t {

  aw_pmd_cmn_clkgen_refdiv_set                    pmd_cmn_clkgen_refdiv_set;
  aw_pmd_cmn_clkgen_refdiv_get                    pmd_cmn_clkgen_refdiv_get;
  aw_pmd_anlt_logical_lane_num_set                pmd_anlt_logical_lane_num_set;
  aw_pmd_anlt_logical_lane_num_get                pmd_anlt_logical_lane_num_get;
  aw_pmd_anlt_auto_neg_adv_ability_set            pmd_anlt_auto_neg_adv_ability_set;
  aw_pmd_anlt_auto_neg_adv_ability_get            pmd_anlt_auto_neg_adv_ability_get;
  aw_pmd_anlt_auto_neg_config_set                 pmd_anlt_auto_neg_config_set;
  aw_pmd_anlt_auto_neg_config_get                 pmd_anlt_auto_neg_config_get;
  aw_pmd_anlt_auto_neg_start_set                  pmd_anlt_auto_neg_start_set;
  aw_pmd_anlt_auto_neg_start_get                  pmd_anlt_auto_neg_start_get;
  aw_pmd_anlt_auto_neg_status_get                 pmd_anlt_auto_neg_status_get;
  aw_pmd_anlt_auto_neg_result_get                 pmd_anlt_auto_neg_result_get;
  aw_pmd_anlt_auto_neg_page_rx_get                pmd_anlt_auto_neg_page_rx_get;
  aw_pmd_anlt_auto_neg_next_page_set              pmd_anlt_auto_neg_next_page_set;
  aw_pmd_anlt_auto_neg_newdef_get                 pmd_anlt_auto_neg_newdef_get;
  aw_pmd_anlt_auto_neg_rs_fec_int_ena_get         pmd_anlt_auto_neg_rs_fec_int_ena_get;
  aw_pmd_anlt_auto_neg_next_page_oui_compare_set  pmd_anlt_auto_neg_next_page_oui_compare_set;
  aw_pmd_anlt_link_training_en_set                pmd_anlt_link_training_en_set;
  aw_pmd_anlt_link_training_en_get                pmd_anlt_link_training_en_get;
  aw_pmd_anlt_link_training_config_set            pmd_anlt_link_training_config_set;
  aw_pmd_anlt_link_training_config_get            pmd_anlt_link_training_config_get;
  aw_pmd_anlt_link_training_prbs_seed_set         pmd_anlt_link_training_prbs_seed_set;
  aw_pmd_anlt_link_training_start_set             pmd_anlt_link_training_start_set;
  aw_pmd_anlt_link_training_start_get             pmd_anlt_link_training_start_get;
  aw_pmd_anlt_link_training_status_get            pmd_anlt_link_training_status_get;
  aw_pmd_anlt_link_training_timeout_enable_set    pmd_anlt_link_training_timeout_enable_set;
  aw_pmd_ctrl_map_en_set                          pmd_ctrl_map_en_set;
  aw_pmd_refclk_termination_set                   pmd_refclk_termination_set;
  aw_pmd_refclk_termination_get                   pmd_refclk_termination_get;
  aw_pmd_rx_termination_set                       pmd_rx_termination_set;
  aw_pmd_rx_termination_get                       pmd_rx_termination_get;
  aw_pmd_force_signal_detect_config_set           pmd_force_signal_detect_config_set;
  aw_pmd_force_signal_detect_config_get           pmd_force_signal_detect_config_get;
  aw_pmd_tx_disable_set                           pmd_tx_disable_set;
  aw_pmd_tx_disable_get                           pmd_tx_disable_get;
  aw_pmd_txfir_config_set                         pmd_txfir_config_set;
  aw_pmd_txfir_config_get                         pmd_txfir_config_get;
  aw_pmd_tx_tap_mode_get                          pmd_tx_tap_mode_get;
  aw_pmd_tx_pam4_precoder_override_set            pmd_tx_pam4_precoder_override_set;
  aw_pmd_tx_pam4_precoder_override_get            pmd_tx_pam4_precoder_override_get;
  aw_pmd_tx_pam4_precoder_enable_set              pmd_tx_pam4_precoder_enable_set;
  aw_pmd_tx_pam4_precoder_enable_get              pmd_tx_pam4_precoder_enable_get;
  aw_pmd_rx_pam4_precoder_override_set            pmd_rx_pam4_precoder_override_set;
  aw_pmd_rx_pam4_precoder_override_get            pmd_rx_pam4_precoder_override_get;
  aw_pmd_rx_pam4_precoder_enable_set              pmd_rx_pam4_precoder_enable_set;
  aw_pmd_rx_pam4_precoder_enable_get              pmd_rx_pam4_precoder_enable_get;
  aw_pmd_remote_loopback_set                      pmd_remote_loopback_set;
  aw_pmd_remote_loopback_get                      pmd_remote_loopback_get;
  aw_pmd_fep_data_set                             pmd_fep_data_set;
  aw_pmd_fep_data_get                             pmd_fep_data_get;
  aw_pmd_fep_clock_set                            pmd_fep_clock_set;
  aw_pmd_fep_clock_get                            pmd_fep_clock_get;
  aw_pmd_tx_dcd_iq_cal                            pmd_tx_dcd_iq_cal;
  aw_pmd_tx_postdiv_loopback_ena_set              pmd_tx_postdiv_loopback_ena_set;
  aw_pmd_tx_postdiv_loopback_ena_get              pmd_tx_postdiv_loopback_ena_get;
  aw_pmd_analog_loopback_set                      pmd_analog_loopback_set;
  aw_pmd_analog_loopback_get                      pmd_analog_loopback_get;
  aw_pmd_fes_loopback_set                         pmd_fes_loopback_set;
  aw_pmd_fes_loopback_get                         pmd_fes_loopback_get;
  aw_pmd_nep_loopback_set                         pmd_nep_loopback_set;
  aw_pmd_nep_loopback_get                         pmd_nep_loopback_get;
  aw_pmd_tx_polarity_set                          pmd_tx_polarity_set;
  aw_pmd_tx_polarity_get                          pmd_tx_polarity_get;
  aw_pmd_rx_polarity_set                          pmd_rx_polarity_set;
  aw_pmd_rx_polarity_get                          pmd_rx_polarity_get;
  aw_pmd_tx_hbridge_set                           pmd_tx_hbridge_set;
  aw_pmd_tx_hbridge_get                           pmd_tx_hbridge_get;
  aw_pmd_rx_dfe_adapt_set                         pmd_rx_dfe_adapt_set;
  aw_pmd_rx_dfe_adapt_get                         pmd_rx_dfe_adapt_get;
  aw_pmd_rx_ctle_adapt_set                        pmd_rx_ctle_adapt_set;
  aw_pmd_rx_ctle_adapt_get                        pmd_rx_ctle_adapt_get;
  aw_pmd_rx_background_adapt_enable_set           pmd_rx_background_adapt_enable_set;
  aw_pmd_rx_background_adapt_enable_get           pmd_rx_background_adapt_enable_get;
  aw_pmd_rx_autoeq_set                            pmd_rx_autoeq_set;
  aw_pmd_rx_autoeq_get                            pmd_rx_autoeq_get;
  aw_pmd_rx_ffe_tap_count_set                     pmd_rx_ffe_tap_count_set;
  aw_pmd_rx_ffe_tap_count_get                     pmd_rx_ffe_tap_count_get;
  aw_pmd_rx_roaming_windows_set                   pmd_rx_roaming_windows_set;
  aw_pmd_rx_roaming_windows_get                   pmd_rx_roaming_windows_get;
  aw_pmd_rx_vga_cap_set                           pmd_rx_vga_cap_set;
  aw_pmd_rx_vga_cap_adapt_set                     pmd_rx_vga_cap_adapt_set;
  aw_pmd_rx_vga_cap_get                           pmd_rx_vga_cap_get;
  aw_pmd_rx_vga_cap_adapt_get                     pmd_rx_vga_cap_adapt_get;
  aw_pmd_rxeq_prbs_set                            pmd_rxeq_prbs_set;
  aw_pmd_rxeq_prbs_get                            pmd_rxeq_prbs_get;
  aw_pmd_rx_c0_adapt_set                          pmd_rx_c0_adapt_set;
  aw_pmd_rx_cdr_offset_set                        pmd_rx_cdr_offset_set;
  aw_pmd_rx_signal_detect_get                     pmd_rx_signal_detect_get;
  aw_pmd_rx_signal_detect_check                   pmd_rx_signal_detect_check;
  aw_pmd_tx_ppm_get                               pmd_tx_ppm_get;
  aw_pmd_rx_ppm_get                               pmd_rx_ppm_get;
  aw_pmd_rx_lock_status_get                       pmd_rx_lock_status_get;
  aw_pmd_rx_dcdiq_get                             pmd_rx_dcdiq_get;
  aw_pmd_tx_dcdiq_get                             pmd_tx_dcdiq_get;
  aw_pmd_rx_afe_get                               pmd_rx_afe_get;
  aw_pmd_rx_invert_datapath                       pmd_rx_invert_datapath;
  aw_pmd_tx_invert_datapath                       pmd_tx_invert_datapath;
  aw_pmd_rx_chk_config_set                        pmd_rx_chk_config_set;
  aw_pmd_rx_chk_config_get                        pmd_rx_chk_config_get;
  aw_pmd_rx_chk_en_set                            pmd_rx_chk_en_set;
  aw_pmd_rx_chk_en_get                            pmd_rx_chk_en_get;
  aw_pmd_rx_chk_lock_state_get                    pmd_rx_chk_lock_state_get;
  aw_pmd_rx_chk_err_count_state_get               pmd_rx_chk_err_count_state_get;
  aw_pmd_rx_chk_err_count_state_clear             pmd_rx_chk_err_count_state_clear;
  aw_pmd_tx_gen_config_set                        pmd_tx_gen_config_set;
  aw_pmd_tx_gen_config_get                        pmd_tx_gen_config_get;
  aw_pmd_tx_gen_en_set                            pmd_tx_gen_en_set;
  aw_pmd_tx_gen_en_get                            pmd_tx_gen_en_get;
  aw_pmd_tx_gen_err_inject_config_set             pmd_tx_gen_err_inject_config_set;
  aw_pmd_tx_gen_err_inject_config_get             pmd_tx_gen_err_inject_config_get;
  aw_pmd_tx_gen_err_inject_en_set                 pmd_tx_gen_err_inject_en_set;
  aw_pmd_tx_gen_err_inject_en_get                 pmd_tx_gen_err_inject_en_get;
  aw_pmd_rx_sweep_demapper                        pmd_rx_sweep_demapper;
  aw_pmd_gen_tx_swap_msb_lsb_set                  pmd_gen_tx_swap_msb_lsb_set;
  aw_pmd_gen_tx_swap_msb_lsb_get                  pmd_gen_tx_swap_msb_lsb_get;
  aw_pmd_gen_rx_swap_msb_lsb_set                  pmd_gen_rx_swap_msb_lsb_set;
  aw_pmd_gen_rx_swap_msb_lsb_get                  pmd_gen_rx_swap_msb_lsb_get;
  aw_pmd_uc_ucode_load                            pmd_uc_ucode_load;
  aw_pmd_pll_lock_max_set                         pmd_pll_lock_max_set;
  aw_pmd_pll_lock_min_set                         pmd_pll_lock_min_set;
  aw_pmd_pll_lock_get                             pmd_pll_lock_get;
  aw_pmd_uc_diag_reg_dump                         pmd_uc_diag_reg_dump;
  aw_pmd_uc_diag_logging_en_set                   pmd_uc_diag_logging_en_set;
  aw_pmd_uc_diag_logging_en_get                   pmd_uc_diag_logging_en_get;
  aw_pmd_iso_ref_ls_en_set                        pmd_iso_ref_ls_en_set;
  aw_pmd_iso_cmn_pstate_set                       pmd_iso_cmn_pstate_set;
  aw_pmd_iso_cmn_pstate_get                       pmd_iso_cmn_pstate_get;
  aw_pmd_iso_cmn_state_req_set                    pmd_iso_cmn_state_req_set;
  aw_pmd_iso_cmn_state_ack_get                    pmd_iso_cmn_state_ack_get;
  aw_pmd_iso_tx_reset_set                         pmd_iso_tx_reset_set;
  aw_pmd_iso_tx_reset_get                         pmd_iso_tx_reset_get;
  aw_pmd_iso_rx_reset_set                         pmd_iso_rx_reset_set;
  aw_pmd_iso_rx_reset_get                         pmd_iso_rx_reset_get;
  aw_pmd_iso_tx_rate_set                          pmd_iso_tx_rate_set;
  aw_pmd_iso_tx_rate_get                          pmd_iso_tx_rate_get;
  aw_pmd_iso_rx_rate_set                          pmd_iso_rx_rate_set;
  aw_pmd_iso_rx_rate_get                          pmd_iso_rx_rate_get;
  aw_pmd_iso_tx_pstate_set                        pmd_iso_tx_pstate_set;
  aw_pmd_iso_tx_pstate_get                        pmd_iso_tx_pstate_get;
  aw_pmd_iso_rx_pstate_set                        pmd_iso_rx_pstate_set;
  aw_pmd_iso_rx_pstate_get                        pmd_iso_rx_pstate_get;
  aw_pmd_iso_tx_width_set                         pmd_iso_tx_width_set;
  aw_pmd_iso_tx_width_get                         pmd_iso_tx_width_get;
  aw_pmd_iso_rx_width_set                         pmd_iso_rx_width_set;
  aw_pmd_iso_rx_width_get                         pmd_iso_rx_width_get;
  aw_pmd_iso_tx_state_req_set                     pmd_iso_tx_state_req_set;
  aw_pmd_iso_rx_state_req_set                     pmd_iso_rx_state_req_set;
  aw_pmd_iso_tx_state_ack_get                     pmd_iso_tx_state_ack_get;
  aw_pmd_iso_rx_state_ack_get                     pmd_iso_rx_state_ack_get;
  aw_pmd_isolate_cmn_set                          pmd_isolate_cmn_set;
  aw_pmd_isolate_cmn_get                          pmd_isolate_cmn_get;
  aw_pmd_isolate_lane_set                         pmd_isolate_lane_set;
  aw_pmd_isolate_lane_tx_set                      pmd_isolate_lane_tx_set;
  aw_pmd_isolate_lane_rx_set                      pmd_isolate_lane_rx_set;
  aw_pmd_isolate_lane_txrx_set                    pmd_isolate_lane_txrx_set;
  aw_pmd_isolate_lane_get                         pmd_isolate_lane_get;
  aw_pmd_cmn_r2l_hsref_sel_set                    pmd_cmn_r2l_hsref_sel_set;
  aw_pmd_cmn_r2l0_lsref_sel_set                   pmd_cmn_r2l0_lsref_sel_set;
  aw_pmd_cmn_r2l1_lsref_sel_set                   pmd_cmn_r2l1_lsref_sel_set;
  aw_pmd_cmn_l2r_hsref_sel_set                    pmd_cmn_l2r_hsref_sel_set;
  aw_pmd_cmn_l2r0_lsref_sel_set                   pmd_cmn_l2r0_lsref_sel_set;
  aw_pmd_cmn_l2r1_lsref_sel_set                   pmd_cmn_l2r1_lsref_sel_set;
  aw_pmd_cmn_r2l_hsref_sel_get                    pmd_cmn_r2l_hsref_sel_get;
  aw_pmd_cmn_r2l0_lsref_sel_get                   pmd_cmn_r2l0_lsref_sel_get;
  aw_pmd_cmn_r2l1_lsref_sel_get                   pmd_cmn_r2l1_lsref_sel_get;
  aw_pmd_cmn_l2r_hsref_sel_get                    pmd_cmn_l2r_hsref_sel_get;
  aw_pmd_cmn_l2r0_lsref_sel_get                   pmd_cmn_l2r0_lsref_sel_get;
  aw_pmd_cmn_l2r1_lsref_sel_get                   pmd_cmn_l2r1_lsref_sel_get;
  aw_pmd_cmn_lsref_sel_set                        pmd_cmn_lsref_sel_set;
  aw_pmd_cmn_lsref_sel_get                        pmd_cmn_lsref_sel_get;
  aw_pmd_pcie_cmn_lsref_25m_set                   pmd_pcie_cmn_lsref_25m_set;
  aw_pmd_pcie_cmn_lsref_25m_get                   pmd_pcie_cmn_lsref_25m_get;
  aw_pmd_gen_tx_en_set                            pmd_gen_tx_en_set;
  aw_pmd_gen_tx_en_get                            pmd_gen_tx_en_get;
  aw_pmd_rx_error_cnt_done_get                    pmd_rx_error_cnt_done_get;
  aw_pmd_iso_request_cmn_state_change             pmd_iso_request_cmn_state_change;
  aw_pmd_iso_request_tx_state_change              pmd_iso_request_tx_state_change;
  aw_pmd_iso_request_rx_state_change              pmd_iso_request_rx_state_change;
  aw_pmd_rx_check_cdr_lock                        pmd_rx_check_cdr_lock;
  aw_pmd_rx_check_bist                            pmd_rx_check_bist;
  aw_pmd_rx_prefec_clear                          pmd_rx_prefec_clear;
  aw_pmd_rx_prefec_enable_get                     pmd_rx_prefec_enable_get;
  aw_pmd_rx_prefec_enable_set                     pmd_rx_prefec_enable_set;
  aw_pmd_rx_prefec_poll                           pmd_rx_prefec_poll;
  aw_pmd_rx_prefec_config_get                     pmd_rx_prefec_config_get;
  aw_pmd_rx_prefec_config_set                     pmd_rx_prefec_config_set;
  aw_pmd_rx_prefec_get_results                    pmd_rx_prefec_get_results;
  aw_pmd_eqeval_type_set                          pmd_eqeval_type_set;
  aw_pmd_eqeval_req_set                           pmd_eqeval_req_set;
  aw_pmd_eqeval_ack_get                           pmd_eqeval_ack_get;
  aw_pmd_eqeval_incdec_get                        pmd_eqeval_incdec_get;
  aw_pmd_rx_equalize                              pmd_rx_equalize;
  aw_pmd_tx_rxdet_req_set                         pmd_tx_rxdet_req_set;
  aw_pmd_tx_rxdet                                 pmd_tx_rxdet;
  aw_pmd_tx_beacon_en_set                         pmd_tx_beacon_en_set;
  aw_pmd_tx_beacon_en_get                         pmd_tx_beacon_en_get;
  aw_pmd_tx_pll_fine_code_get                     pmd_tx_pll_fine_code_get;
  aw_pmd_tx_pll_coarse_code_get                   pmd_tx_pll_coarse_code_get;
  aw_pmd_rx_pll_fine_code_get                     pmd_rx_pll_fine_code_get;
  aw_pmd_rx_pll_coarse_code_get                   pmd_rx_pll_coarse_code_get;
  aw_pmd_cmn_pll_fine_code_get                    pmd_cmn_pll_fine_code_get;
  aw_pmd_cmn_pll_coarse_code_get                  pmd_cmn_pll_coarse_code_get;
  aw_pmd_rd_data_pipeline_stages_set              pmd_rd_data_pipeline_stages_set;
  aw_pmd_rd_data_pipeline_stages_get              pmd_rd_data_pipeline_stages_get;
  aw_pmd_measure_pmon                             pmd_measure_pmon;
  aw_pmd_atest_en                                 pmd_atest_en;
  aw_pmd_atest_cmn_capture                        pmd_atest_cmn_capture;
  aw_pmd_atest_tx_capture                         pmd_atest_tx_capture;
  aw_pmd_atest_rx_a_capture                       pmd_atest_rx_a_capture;
  aw_pmd_atest_rx_b_capture                       pmd_atest_rx_b_capture;
  aw_pmd_atest_adc_power                          pmd_atest_adc_power;
  aw_pmd_atest_adc_temp_capture                   pmd_atest_adc_temp_capture;
  aw_pmd_atest_adc_temp_get                       pmd_atest_adc_temp_get;
  aw_pmd_rx_cdr_lock_get                          pmd_rx_cdr_lock_get;
  aw_pmd_lcpll_vco_counter_get                    pmd_lcpll_vco_counter_get;
  aw_pmd_rx_cdr_offset_get                        pmd_rx_cdr_offset_get;
  aw_pmd_read_status                              pmd_read_status;
  aw_pmd_read_status                              pmd_read_status2;
  aw_pmd_pause_background                         pmd_pause_background;
  aw_pmd_tracebuffer_config_enable                pmd_tracebuffer_config_enable;
  aw_pmd_tracebuffer_config_get                   pmd_tracebuffer_config_get;
  aw_pmd_tracebuffer_config_set                   pmd_tracebuffer_config_set;
  aw_pmd_read_tracebuffer                         pmd_read_tracebuffer;
  aw_pmd_convert_data_signed                      pmd_convert_data_signed;
  aw_pmd_read_tracebuffer_adc                     pmd_read_tracebuffer_adc;
  aw_pmd_tbus_client_config_get                   pmd_tbus_client_config_get;
  aw_pmd_tbus_client_config_set                   pmd_tbus_client_config_set;
  aw_pmd_read_tracebuffer_demapper                pmd_read_tracebuffer_demapper;
  aw_pmd_read_tracebuffer_general                 pmd_read_tracebuffer_general;
  aw_pmd_read_tracebuffer_ffe                     pmd_read_tracebuffer_ffe;
  aw_pmd_read_tracebuffer_itr_dlpf_int            pmd_read_tracebuffer_itr_dlpf_int;
  aw_pmd_read_tracebuffer_quantizer_err           pmd_read_tracebuffer_quantizer_err;
  aw_pmd_cmn_ssc_config                           pmd_cmn_ssc_config;
  aw_pmd_cmn_ssc_en_set                           pmd_cmn_ssc_en_set;
  aw_pmd_sram_clk_div_set                         pmd_sram_clk_div_set;
  aw_pmd_sram_clk_div_get                         pmd_sram_clk_div_get;
  aw_pmd_rx_burst_mode_config_set                 pmd_rx_burst_mode_config_set;
  aw_pmd_rx_burst_mode_config_get                 pmd_rx_burst_mode_config_get;
  aw_pmd_rx_burst_err_cnt_get                     pmd_rx_burst_err_cnt_get;
  aw_pmd_rx_burst_mode_stats_get                  pmd_rx_burst_mode_stats_get;
  aw_pmd_rx_gray_code_mapping_get                 pmd_rx_gray_code_mapping_get;
  aw_pmd_rx_gray_code_mapping_set                 pmd_rx_gray_code_mapping_set;
  aw_pmd_tx_gray_code_mapping_get                 pmd_tx_gray_code_mapping_get;
  aw_pmd_tx_gray_code_mapping_set                 pmd_tx_gray_code_mapping_set;
  aw_pmd_tx_perf_settings                         pmd_tx_perf_settings;
  aw_pmd_cmn_bias_bandgap_force_startup           pmd_cmn_bias_bandgap_force_startup;
  aw_pmd_sris_set                                 pmd_sris_set;
  aw_pmd_sris_get                                 pmd_sris_get;
  aw_pmd_rx_active_branches_get                   pmd_rx_active_branches_get;
  aw_pmd_fw_version_get                           pmd_fw_version_get;
  aw_pmd_rx_dfe_ratio_set                         pmd_rx_dfe_ratio_set;
  aw_pmd_rx_dfe_ratio_get                         pmd_rx_dfe_ratio_get;


  // bfn defined fns
  aw_pmd_mss_reset                               pmd_mss_reset;
  aw_pmd_fw_load                                 pmd_fw_load;
  aw_pmd_one_time_pgm                            pmd_one_time_pgm;
  aw_pmd_cur_rate_width_pstate                   pmd_cur_rate_width_pstate;
  aw_pmd_rxmfsm_eq_check_rxdisable_set           pmd_rxmfsm_eq_check_rxdisable_set;
  aw_pmd_lt_info_get                             pmd_lt_info_get;
  aw_pmd_rd_csr                                  pmd_rd_csr;
  aw_pmd_wr_csr                                  pmd_wr_csr;
  aw_pmd_reg_defs_get                            pmd_reg_defs_get;
  aw_pmd_speed_to_rate_and_width                 pmd_speed_to_rate_and_width;
  aw_pmd_rx_dig_pwr_det_threshold_get            pmd_rx_dig_pwr_det_threshold_get;
  aw_pmd_rx_dig_pwr_det_threshold_set            pmd_rx_dig_pwr_det_threshold_set;

  // virtual field APIs
#include "vfld_vec_name.h"

} aw_serdes_driver_vector_t;

