import BaseFunction.IP.IP_BlueJay_L2_pam4 as BlueJay_l2
from regfunc import inject_func
import credo

def load_basefunction_pam4(chip):
    inject_func(chip.PAM50, BlueJay_l2.tx_prbs_en_pam4)
    inject_func(chip.PAM50, BlueJay_l2.tx_test_patt_pam4)
    #inject_func(chip.PAM50, BlueJay_l2.tx_prbs_en_pam4)
    inject_func(chip.PAM50, BlueJay_l2.tx_prbs_mode_pam4)
    inject_func(chip.PAM50, BlueJay_l2.err_inject)
    inject_func(chip.PAM50, BlueJay_l2.tx_taps)
    inject_func(chip.NRZ25, BlueJay_l2.tx_taps)
    inject_func(chip.PAM50, BlueJay_l2.tx_taps_sh)
    inject_func(chip.PAM50, BlueJay_l2.tx_gray)
    inject_func(chip.PAM50, BlueJay_l2.tx_precoder)
    inject_func(chip.PAM50, BlueJay_l2.tx_pol_pam4)
    inject_func(chip.PAM50, BlueJay_l2.tx_pol_flip_pam4)
    inject_func(chip.PAM50, BlueJay_l2.prbs_rst_pam4)
    inject_func(chip.PAM50, BlueJay_l2.ready_pam4)
    inject_func(chip.PAM50, BlueJay_l2.agcgain)
    inject_func(chip.NRZ25, BlueJay_l2.agcgain)
    inject_func(chip.PAM50, BlueJay_l2.skef)
    inject_func(chip.NRZ25, BlueJay_l2.skef)
    inject_func(chip.PAM50, BlueJay_l2.edge)
    inject_func(chip.NRZ25, BlueJay_l2.edge)
    inject_func(chip.PAM50, BlueJay_l2.f13)
    inject_func(chip.PAM50, BlueJay_l2.ctle_pam4)
    inject_func(chip.PAM50, BlueJay_l2.eye_pam4)
    inject_func(chip.LANE, BlueJay_l2.ber_pam4)
    inject_func(chip.PAM50, BlueJay_l2.delta_pam4)
    inject_func(chip.PAM50, BlueJay_l2.dac_pam4)
    inject_func(chip.PAM50, BlueJay_l2.ready_pam4)
    inject_func(chip.PAM50, BlueJay_l2.sig_det_pam4)
    inject_func(chip.PAM50, BlueJay_l2.phy_rdy_pam4)
    inject_func(chip.PAM50, BlueJay_l2.sm_cont_pam4)
    inject_func(chip.NRZ25, BlueJay_l2.dc_gain)
    inject_func(chip.PAM50, BlueJay_l2.dc_gain)
    inject_func(chip.PAM50, BlueJay_l2.ctle_map_pam4)
    inject_func(chip.PAM50, BlueJay_l2.rx_checker_pam4)
    inject_func(chip.PAM50, BlueJay_l2.rx_prbs_mode_pam4)
    inject_func(chip.PAM50, BlueJay_l2.get_err_pam4)
    inject_func(chip.PAM50, BlueJay_l2.rx_pol_pam4)
    inject_func(chip.PAM50, BlueJay_l2.rx_pol_flip_pam4)
    inject_func(chip.PAM50, BlueJay_l2.set_tx_lane)
    inject_func(chip.PAM50, BlueJay_l2.set_rx_lane)
    inject_func(chip.PAM50, BlueJay_l2.gc)
    inject_func(chip.PAM50, BlueJay_l2.pc)
    inject_func(chip.PAM50, BlueJay_l2.msblsb)
    inject_func(chip.LANE, BlueJay_l2.get_lane_pll)
    #inject_func(chip.NRZ25, BlueJay_l2.get_lane_pll)
    inject_func(chip.PAM50, BlueJay_l2.lr_pam4)
    inject_func(chip.NRZ25, BlueJay_l2.state_pam4)
    inject_func(chip.PAM50, BlueJay_l2.latch_data_pam4)
    inject_func(chip.PAM50, BlueJay_l2.latch_data_release_pam4)
    inject_func(chip.PAM50, BlueJay_l2.bp1)
    inject_func(chip.PAM50, BlueJay_l2.bp2)
    inject_func(chip.PAM50, BlueJay_l2.ffe_taps)





