/*
** ? 2020 Alphawave IP Inc.
*/

/**
 * @brief Alphawave Alphacore RX DSP Function.
 *
 * @file aw_pmd_rx_dsp_get.c
 *
 */

#include "aw_alphacore.h"
#include "aw_pmd_rx_dsp_get.h"

/**
 *
 * Reports the adapted receiver digital signal processing (DSP) parameters,
 * used for debugging signal integrity issues involving the lane receiver.
 * All the below DSP params are signed and have a custom precision
 *
 */
int aw_pmd_16ln_rx_dsp_get(mss_access_t *mss, uint32_t branch, aw_dsp_param_t *dsp_info){
    // branch: branch for which dsp statistics are to be retrieved
    CHECK(pmd_write_field(mss, RX_DATABLOCK_OFFSET_REG1_ADDR, RX_DATABLOCK_OFFSET_REG1_BRANCH_SEL_A_MASK, RX_DATABLOCK_OFFSET_REG1_BRANCH_SEL_A_OFFSET, branch));
    CHECK(pmd_read_field(mss, RX_DATABLOCK_OFFSET_RDREG9_ADDR, RX_DATABLOCK_OFFSET_RDREG9_OFFSET_NT_MASK, RX_DATABLOCK_OFFSET_RDREG9_OFFSET_NT_OFFSET, &(dsp_info->dc_offset) ));
    CHECK(pmd_write_field(mss, RX_FFE_ADAPT_REG1_ADDR, RX_FFE_ADAPT_REG1_BRANCH_SEL_A_MASK, RX_FFE_ADAPT_REG1_BRANCH_SEL_A_OFFSET, branch));

    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG0_ADDR, RX_FFE_ADAPT_COEF_RDREG0_TAP0_NT_MASK, RX_FFE_ADAPT_COEF_RDREG0_TAP0_NT_OFFSET,   &(dsp_info->ffe[0]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG0_ADDR, RX_FFE_ADAPT_COEF_RDREG0_TAP1_NT_MASK, RX_FFE_ADAPT_COEF_RDREG0_TAP1_NT_OFFSET,   &(dsp_info->ffe[1]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG0_ADDR, RX_FFE_ADAPT_COEF_RDREG0_TAP2_NT_MASK, RX_FFE_ADAPT_COEF_RDREG0_TAP2_NT_OFFSET,   &(dsp_info->ffe[2]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG0_ADDR, RX_FFE_ADAPT_COEF_RDREG0_TAP3_NT_MASK, RX_FFE_ADAPT_COEF_RDREG0_TAP3_NT_OFFSET,   &(dsp_info->ffe[3]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG0_ADDR, RX_FFE_ADAPT_COEF_RDREG0_TAP4_NT_MASK, RX_FFE_ADAPT_COEF_RDREG0_TAP4_NT_OFFSET,   &(dsp_info->ffe[4]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG0_ADDR, RX_FFE_ADAPT_COEF_RDREG0_TAP5_NT_MASK, RX_FFE_ADAPT_COEF_RDREG0_TAP5_NT_OFFSET,   &(dsp_info->ffe[5]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG1_ADDR, RX_FFE_ADAPT_COEF_RDREG1_TAP6_NT_MASK, RX_FFE_ADAPT_COEF_RDREG1_TAP6_NT_OFFSET,   &(dsp_info->ffe[6]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG1_ADDR, RX_FFE_ADAPT_COEF_RDREG1_TAP7_NT_MASK, RX_FFE_ADAPT_COEF_RDREG1_TAP7_NT_OFFSET,   &(dsp_info->ffe[7]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG1_ADDR, RX_FFE_ADAPT_COEF_RDREG1_TAP8_NT_MASK, RX_FFE_ADAPT_COEF_RDREG1_TAP8_NT_OFFSET,   &(dsp_info->ffe[8]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG1_ADDR, RX_FFE_ADAPT_COEF_RDREG1_TAP9_NT_MASK, RX_FFE_ADAPT_COEF_RDREG1_TAP9_NT_OFFSET,   &(dsp_info->ffe[9]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG2_ADDR, RX_FFE_ADAPT_COEF_RDREG2_TAP10_NT_MASK, RX_FFE_ADAPT_COEF_RDREG2_TAP10_NT_OFFSET,   &(dsp_info->ffe[10]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG2_ADDR, RX_FFE_ADAPT_COEF_RDREG2_TAP11_NT_MASK, RX_FFE_ADAPT_COEF_RDREG2_TAP11_NT_OFFSET,   &(dsp_info->ffe[11]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG2_ADDR, RX_FFE_ADAPT_COEF_RDREG2_TAP12_NT_MASK, RX_FFE_ADAPT_COEF_RDREG2_TAP12_NT_OFFSET,   &(dsp_info->ffe[12]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG3_ADDR, RX_FFE_ADAPT_COEF_RDREG3_TAP13_NT_MASK, RX_FFE_ADAPT_COEF_RDREG3_TAP13_NT_OFFSET,   &(dsp_info->ffe[13]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG3_ADDR, RX_FFE_ADAPT_COEF_RDREG3_TAP14_NT_MASK, RX_FFE_ADAPT_COEF_RDREG3_TAP14_NT_OFFSET,   &(dsp_info->ffe[14]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG3_ADDR, RX_FFE_ADAPT_COEF_RDREG3_TAP15_NT_MASK, RX_FFE_ADAPT_COEF_RDREG3_TAP15_NT_OFFSET,   &(dsp_info->ffe[15]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG4_ADDR, RX_FFE_ADAPT_COEF_RDREG4_TAP16_NT_MASK, RX_FFE_ADAPT_COEF_RDREG4_TAP16_NT_OFFSET,   &(dsp_info->ffe[16]) ));
    CHECK(pmd_read_field(mss, RX_FFE_ADAPT_COEF_RDREG4_ADDR, RX_FFE_ADAPT_COEF_RDREG4_TAP17_NT_MASK, RX_FFE_ADAPT_COEF_RDREG4_TAP17_NT_OFFSET,   &(dsp_info->ffe[17]) ));


    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG1_ADDR, RXEQSTORE0_TAP_REG1_TAP0_NT_MASK, RXEQSTORE0_TAP_REG1_TAP0_NT_OFFSET,   &(dsp_info->pre_ffe[0]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG1_ADDR, RXEQSTORE0_TAP_REG1_TAP1_NT_MASK, RXEQSTORE0_TAP_REG1_TAP1_NT_OFFSET,   &(dsp_info->pre_ffe[1]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG1_ADDR, RXEQSTORE0_TAP_REG1_TAP2_NT_MASK, RXEQSTORE0_TAP_REG1_TAP2_NT_OFFSET,   &(dsp_info->pre_ffe[2]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG1_ADDR, RXEQSTORE0_TAP_REG1_TAP3_NT_MASK, RXEQSTORE0_TAP_REG1_TAP3_NT_OFFSET,   &(dsp_info->pre_ffe[3]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG1_ADDR, RXEQSTORE0_TAP_REG1_TAP4_NT_MASK, RXEQSTORE0_TAP_REG1_TAP4_NT_OFFSET,   &(dsp_info->pre_ffe[4]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG1_ADDR, RXEQSTORE0_TAP_REG1_TAP5_NT_MASK, RXEQSTORE0_TAP_REG1_TAP5_NT_OFFSET,   &(dsp_info->pre_ffe[5]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG2_ADDR, RXEQSTORE0_TAP_REG2_TAP6_NT_MASK, RXEQSTORE0_TAP_REG2_TAP6_NT_OFFSET,   &(dsp_info->pre_ffe[6]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG2_ADDR, RXEQSTORE0_TAP_REG2_TAP7_NT_MASK, RXEQSTORE0_TAP_REG2_TAP7_NT_OFFSET,   &(dsp_info->pre_ffe[7]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG2_ADDR, RXEQSTORE0_TAP_REG2_TAP8_NT_MASK, RXEQSTORE0_TAP_REG2_TAP8_NT_OFFSET,   &(dsp_info->pre_ffe[8]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG2_ADDR, RXEQSTORE0_TAP_REG2_TAP9_NT_MASK, RXEQSTORE0_TAP_REG2_TAP9_NT_OFFSET,   &(dsp_info->pre_ffe[9]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG3_ADDR, RXEQSTORE0_TAP_REG3_TAP10_NT_MASK, RXEQSTORE0_TAP_REG3_TAP10_NT_OFFSET,   &(dsp_info->pre_ffe[10]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG3_ADDR, RXEQSTORE0_TAP_REG3_TAP11_NT_MASK, RXEQSTORE0_TAP_REG3_TAP11_NT_OFFSET,   &(dsp_info->pre_ffe[11]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG3_ADDR, RXEQSTORE0_TAP_REG3_TAP12_NT_MASK, RXEQSTORE0_TAP_REG3_TAP12_NT_OFFSET,   &(dsp_info->pre_ffe[12]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG4_ADDR, RXEQSTORE0_TAP_REG4_TAP13_NT_MASK, RXEQSTORE0_TAP_REG4_TAP13_NT_OFFSET,   &(dsp_info->pre_ffe[13]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG4_ADDR, RXEQSTORE0_TAP_REG4_TAP14_NT_MASK, RXEQSTORE0_TAP_REG4_TAP14_NT_OFFSET,   &(dsp_info->pre_ffe[14]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG4_ADDR, RXEQSTORE0_TAP_REG4_TAP15_NT_MASK, RXEQSTORE0_TAP_REG4_TAP15_NT_OFFSET,   &(dsp_info->pre_ffe[15]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG5_ADDR, RXEQSTORE0_TAP_REG5_TAP16_NT_MASK, RXEQSTORE0_TAP_REG5_TAP16_NT_OFFSET,   &(dsp_info->pre_ffe[16]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE0_TAP_REG5_ADDR, RXEQSTORE0_TAP_REG5_TAP17_NT_MASK, RXEQSTORE0_TAP_REG5_TAP17_NT_OFFSET,   &(dsp_info->pre_ffe[17]) ));


    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG1_ADDR, RXEQSTORE1_TAP_REG1_TAP0_NT_MASK, RXEQSTORE1_TAP_REG1_TAP0_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[0]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG1_ADDR, RXEQSTORE1_TAP_REG1_TAP1_NT_MASK, RXEQSTORE1_TAP_REG1_TAP1_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[1]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG1_ADDR, RXEQSTORE1_TAP_REG1_TAP2_NT_MASK, RXEQSTORE1_TAP_REG1_TAP2_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[2]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG1_ADDR, RXEQSTORE1_TAP_REG1_TAP3_NT_MASK, RXEQSTORE1_TAP_REG1_TAP3_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[3]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG1_ADDR, RXEQSTORE1_TAP_REG1_TAP4_NT_MASK, RXEQSTORE1_TAP_REG1_TAP4_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[4]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG1_ADDR, RXEQSTORE1_TAP_REG1_TAP5_NT_MASK, RXEQSTORE1_TAP_REG1_TAP5_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[5]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG2_ADDR, RXEQSTORE1_TAP_REG2_TAP6_NT_MASK, RXEQSTORE1_TAP_REG2_TAP6_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[6]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG2_ADDR, RXEQSTORE1_TAP_REG2_TAP7_NT_MASK, RXEQSTORE1_TAP_REG2_TAP7_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[7]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG2_ADDR, RXEQSTORE1_TAP_REG2_TAP8_NT_MASK, RXEQSTORE1_TAP_REG2_TAP8_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[8]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG2_ADDR, RXEQSTORE1_TAP_REG2_TAP9_NT_MASK, RXEQSTORE1_TAP_REG2_TAP9_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[9]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG3_ADDR, RXEQSTORE1_TAP_REG3_TAP10_NT_MASK, RXEQSTORE1_TAP_REG3_TAP10_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[10]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG3_ADDR, RXEQSTORE1_TAP_REG3_TAP11_NT_MASK, RXEQSTORE1_TAP_REG3_TAP11_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[11]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG3_ADDR, RXEQSTORE1_TAP_REG3_TAP12_NT_MASK, RXEQSTORE1_TAP_REG3_TAP12_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[12]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG4_ADDR, RXEQSTORE1_TAP_REG4_TAP13_NT_MASK, RXEQSTORE1_TAP_REG4_TAP13_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[13]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG4_ADDR, RXEQSTORE1_TAP_REG4_TAP14_NT_MASK, RXEQSTORE1_TAP_REG4_TAP14_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[14]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG4_ADDR, RXEQSTORE1_TAP_REG4_TAP15_NT_MASK, RXEQSTORE1_TAP_REG4_TAP15_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[15]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG5_ADDR, RXEQSTORE1_TAP_REG5_TAP16_NT_MASK, RXEQSTORE1_TAP_REG5_TAP16_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[16]) ));
    CHECK(pmd_read_field(mss, RXEQSTORE1_TAP_REG5_ADDR, RXEQSTORE1_TAP_REG5_TAP17_NT_MASK, RXEQSTORE1_TAP_REG5_TAP17_NT_OFFSET,   &(dsp_info->pre_dfe_ffe[17]) ));


    CHECK(pmd_write_field(mss, RX_DFE_ADAPT_REG1_ADDR, RX_DFE_ADAPT_REG1_BRANCH_SEL_A_MASK, RX_DFE_ADAPT_REG1_BRANCH_SEL_A_OFFSET, branch));
    CHECK(pmd_read_field(mss, RX_DFE_ADAPT_RDREG9_ADDR, RX_DFE_ADAPT_RDREG9_COEF_NT_MASK, RX_DFE_ADAPT_RDREG9_COEF_NT_OFFSET, &(dsp_info->dfe) ));

    CHECK(pmd_write_field(mss, RX_SLICER_THRESHOLD_REG1_ADDR, RX_SLICER_THRESHOLD_REG1_BRANCH_SEL_A_MASK, RX_SLICER_THRESHOLD_REG1_BRANCH_SEL_A_OFFSET, branch));
    CHECK(pmd_read_field(mss, RX_SLICER_THRESHOLD_RDREG13_ADDR, RX_SLICER_THRESHOLD_RDREG13_EH_NT_MASK, RX_SLICER_THRESHOLD_RDREG13_EH_NT_OFFSET, &(dsp_info->thresholds.eh) ));
    CHECK(pmd_read_field(mss, RX_SLICER_THRESHOLD_RDREG13_ADDR, RX_SLICER_THRESHOLD_RDREG13_EZ_NT_MASK, RX_SLICER_THRESHOLD_RDREG13_EZ_NT_OFFSET, &(dsp_info->thresholds.ez) ));
    CHECK(pmd_read_field(mss, RX_SLICER_THRESHOLD_RDREG13_ADDR, RX_SLICER_THRESHOLD_RDREG13_EL_NT_MASK, RX_SLICER_THRESHOLD_RDREG13_EL_NT_OFFSET, &(dsp_info->thresholds.el) ));
    CHECK(pmd_read_field(mss, RX_SLICER_THRESHOLD_RDREG14_ADDR, RX_SLICER_THRESHOLD_RDREG14_LOW_NT_MASK, RX_SLICER_THRESHOLD_RDREG14_LOW_NT_OFFSET, &(dsp_info->thresholds.thres_low) ));
    CHECK(pmd_read_field(mss, RX_SLICER_THRESHOLD_RDREG14_ADDR, RX_SLICER_THRESHOLD_RDREG14_UPP_NT_MASK, RX_SLICER_THRESHOLD_RDREG14_UPP_NT_OFFSET, &(dsp_info->thresholds.thres_hi) ));

    CHECK(pmd_write_field(mss, RX_SLICER_TARGET_REG1_ADDR, RX_SLICER_TARGET_REG1_BRANCH_SEL_A_MASK, RX_SLICER_TARGET_REG1_BRANCH_SEL_A_OFFSET, branch));
    CHECK(pmd_read_field(mss, RX_SLICER_TARGET_RDREG13_ADDR, RX_SLICER_TARGET_RDREG13_EL3_NT_MASK, RX_SLICER_TARGET_RDREG13_EL3_NT_OFFSET, &(dsp_info->slicers.el3) ));
    CHECK(pmd_read_field(mss, RX_SLICER_TARGET_RDREG13_ADDR, RX_SLICER_TARGET_RDREG13_EL1_NT_MASK, RX_SLICER_TARGET_RDREG13_EL1_NT_OFFSET, &(dsp_info->slicers.el1) ));
    CHECK(pmd_read_field(mss, RX_SLICER_TARGET_RDREG13_ADDR, RX_SLICER_TARGET_RDREG13_EH1_NT_MASK, RX_SLICER_TARGET_RDREG13_EH1_NT_OFFSET, &(dsp_info->slicers.eh1) ));
    CHECK(pmd_read_field(mss, RX_SLICER_TARGET_RDREG14_ADDR, RX_SLICER_TARGET_RDREG14_EH3_NT_MASK, RX_SLICER_TARGET_RDREG14_EH3_NT_OFFSET, &(dsp_info->slicers.eh3) ));

#if 0 // for mss-dump2
    // Print out target related info
    USR_PRINTF("Branch |   EL3   |   EL1   |   EH1   |   EH3   \n");
    USR_PRINTF("  %d  |   %d   |   %d   |   %d   |   %d   \n", branch, dsp_info->slicers.el3, dsp_info->slicers.el1, dsp_info->slicers.eh1, dsp_info->slicers.eh3);
#endif
    return AW_ERR_CODE_NONE;
}
